version: '3.8'

services:
  bulkybookweb:  
    image: bulkyapp
    #build:
    #    context: .
    #    dockerfile: Dockerfile
    #depends_on: 
    #    - bulkybookweb_database
    ports:
        - "5000:80"
    networks:
        - webapp-network
   
  bulkybookweb_database:
    image: bulkyapp_database
    #environment:
    #    ACCEPT_EULA: Y
    #    MSSQL_SA_PASSWORD: Santababara200@
    ports:
        - "1433:1433"
    #volumes:
    #  - ./seed-data:/seed-datadok
    #  - dbdata:/var/opt/mssql
    networks:
        - webapp-network
    #command: ["/bin/bash", "-c", "/seed-data/wait-for-sql.sh && /seed-data/setup-db.sh"]

#volumes:
#    dbdata:

networks:
  webapp-network:
    driver: bridge